pool:
  vmImage: ubuntu-latest

steps:
- script: |
    apt-get install libmpich-dev
  displayName: Install system packages
- script: |
    mkdir -p "$HOME/.local/bin"
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
  displayName: Install Stack
- script: |
    export PATH="$HOME/.local/bin:$PATH"
    stack --no-terminal --install-ghc build --test --only-dependencies
  displayName: Build Dependencies
- script: |
    export PATH="$HOME/.local/bin:$PATH"
    stack build --test --no-run-tests --haddock --no-haddock-deps
  displayName: Build Package
- script: |
    set -euxo pipefail
    mpiexec stack exec version
    mpiexec -n 3 stack exec example1
    mpiexec -n 3 stack exec example2
    mpiexec -n 3 stack exec -- $(stack path --dist-dir)/build/mpi-test/mpi-test
    mpiexec -n 3 stack exec -- $(stack path --dist-dir)/build/mpi-test-storable/mpi-test-storable
  displayName: Run examples and tests
