# This is the complex Azure configuration, which is intended for use
# on open source libraries which need compatibility across multiple GHC
# versions, must work with cabal-install, and should be
# cross-platform. For more information and other options, see:
#
# https://docs.haskellstack.org/en/stable/azure_ci/
#
# For better organization, you split various jobs into seprate parts
# and each of them are controlled via individual file.
jobs:
- template: ./.azure/azure-linux-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    os: linux

#TODO - template: ./.azure/azure-osx-template.yml
#TODO   parameters:
#TODO     name: macOS
#TODO     vmImage: macOS-10.14
#TODO     os: osx
#TODO 
#TODO - template: ./.azure/azure-windows-template.yml
#TODO   parameters:
#TODO    name: Windows
#TODO    vmImage: vs2017-win2016
#TODO    os: windows
