version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.12
    working_directory: /home/stackage
    steps:
      - checkout
      - restore_cache:
          key: cache-lts-12.12
      - run: sudo apt update
      - run: sudo apt -y install libopenmpi-dev openmpi-bin
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: cache-lts-12.12
          paths:
            - ~/.stack
      - run: stack install --haddock --test --no-run-tests --no-terminal --system-ghc
      - run : mpirun --allow-run-as-root --mca btl self,vader -np 3 stack exec $(stack path --dist-dir)/build/mpi-hs-test-suite/mpi-hs-test-suite
